### ISSUE TITLE
AttributeError: 'VideoWidget' object has no attribute 'getImageItem'

### ISSUE THREAD

**Issue by yrzhanov** [espros/epc-tofcam-toolkit#1]
I installed the package according to the instructions. The GUI opens and connects to the camera. However, neither compiled version (tofcam660.EXE) nor development version allow to save png or raw with the following message:
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\epc\tofCam_gui\gui_tofCams.py", line 64, in _save_png
    self.imageView.getImageItem().save(filePath + '.png')
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'VideoWidget' object has no attribute 'getImageItem'
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\epc\tofCam_gui\gui_tofCams.py", line 59, in _save_raw
    test = self.imageView.getImageItem().image
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'VideoWidget' object has no attribute 'getImageItem'

Could it be due to incompatibility between Python (I'm using 3.11) and PySide6 (I'm using 6.6.2)?

**Comment by epc-ake** [comment]
Hi and sorry for the late reply. 
This is currently a known bug and will be fixed in the next release.
